<?php


namespace App\Constant;


class UserManagementConstants
{
    const ROLE_NOT_AVAILABLE = 'ROLE_NOT_AVAILABLE';

    const NOT_AUTHORIZED = 'NOT_AUTHORIZED';

    const USER_NOT_AVAILABLE = 'USER_NOT_AVAILABLE';

    const GROUP_NOT_EMPTY = 'GROUP_NOT_EMPTY';

    const GROUP_NOT_AVAILABLE='GROUP_NOT_AVAILABLE';

    const INITIATOR_NOT_AVAILABLE='INITIATOR_NOT_AVAILABLE';

    const GROUP_NOT_ASSIGNED='GROUP_NOT_ASSIGNED';

    const GROUP_ALREADY_ASSIGNED='GROUP_ALREADY_ASSIGNED';


}